# Enterprises that use AI Worldwide

In [1]:
import pandas as pd
Enterprises = pd.read_csv("C:/Users/Jhonnatan/Documents/GitHub/Impact-of-AI-in-organizations/Datasets/EnterpriseAI.csv")
Enterprises.head()

,Name,Url,Total Funding,Funding Stage,Description,Year Founded,Exit Status,Location,State,Employees,Twitter Followers,LinkedIn Id,Category
0,NetBase Solutions,netbase.com,84600000.0,Late Stage,With the NetBase real-time social media monito...,2004.0,Private,"Mountain View, California, CA",CA,140,8882.0,57753.0,Consumer marketing
1,Salesforce,salesforce.com,102910000.0,Late Stage,Salesforce is the Customer Success Platform. O...,1999.0,Public,"San Francisco, CA",CA,25000,328765.0,3185.0,B2B sales and marketing
2,GumGum,gumgum.com,36825000.0,Series C,GumGum’s mission is to add value to every onli...,2008.0,Private,"Santa Monica, California, CA",CA,230,1849.0,167379.0,Consumer marketing
3,Lexalytics,lexalytics.com,0.0,None Listed,Text Analytics & Survey Analysis with highly c...,2003.0,Private,"Amherst, MA",MA,40,21052.0,145596.0,Consumer marketing
4,FusionOps,fusionops.com,43656544.0,Series C,Mine the world’s information and makes it acti...,1999.0,Private,"Mountain View, California, CA",CA,180,503.0,115300.0,Industrials and manufacturing

# AI Tools

In [2]:
import pandas as pd
tools = pd.read_csv("C:/Users/Jhonnatan/Documents/GitHub/Impact-of-AI-in-organizations/Datasets/aitools.csv")
tools.head()
#tools.describe()

,tool_mage_url,tool,tool_description,category,upvotes,tags
0,https://uploads-ssl.webflow.com/63994dae103371...,Codeium,"Helps developers understand, modify, and test ...",Generative Code,1987,NaN
1,https://uploads-ssl.webflow.com/63994dae103371...,LeiaPix,Upload an image and turn it into a 3D animation,Image Improvement,1779,Generative Video
2,https://uploads-ssl.webflow.com/63994dae103371...,GPT-3 Playground (OpenAI),Free AI writing tool - Let the AI generate any...,Copywriting,1433,Research
3,https://uploads-ssl.webflow.com/63994dae103371...,BlueWillow,AI-powered image generating tool in Discord,Generative Art,1230,Matt's Picks
4,https://uploads-ssl.webflow.com/63994dae103371...,Character.AI,Have chat conversations with AI characters,Chat,954,For Fun

In [3]:
import pandas as pd
tools_2 = pd.read_csv("C:/Users/Jhonnatan/Documents/GitHub/Impact-of-AI-in-organizations/Datasets/futuretools.csv")
tools_2.head()
# tools_2.describe()

,tool_mage_url,tool,tool_description,category,upvotes,tags
0,https://global-uploads.webflow.com/63994dae103...,Inbox Narrator,An app for email summaries delivered by a voic...,Productivity,1,NaN
1,https://global-uploads.webflow.com/63994dae103...,ChatTube,A Google Chrome Extension to chat with any you...,Chat,5,NaN
2,https://global-uploads.webflow.com/63994dae103...,Bito,A tool to generate custom designs for any proj...,Generative Art,3,NaN
3,https://global-uploads.webflow.com/63994dae103...,Bagasura,"A platform for bug tracking, streamlining work...",Productivity,2,NaN
4,https://global-uploads.webflow.com/63994dae103...,CometCore AI,A chat platform for automating tasks and creat...,Chat,10,NaN

# AI info French Govermment

In [4]:
import pandas as pd
research = pd.read_excel("C:/Users/Jhonnatan/Documents/GitHub/Impact-of-AI-in-organizations/Datasets/AI_eco_gouvFR.xlsx")
research.head()
#research.describe()

,title,description,URL
0,Biocides,modifiant la directive 98/8/CE du Parlement eu...,https://www.economie.gouv.fr/dgccrf/publicatio...
1,Transformation numérique : les aides aux entre...,Francenum.gouv.fr propose des conseils concern...,https://www.economie.gouv.fr/cedef/aides-numer...
2,Rapports 2023,l'industrie de la santé chez Dassault Systèmes...,https://www.economie.gouv.fr/cge/rapports2023
3,Diversité et égalité des chances : Bercy accue...,Besoin en compétences : comment l'immigration ...,https://www.economie.gouv.fr/sommet-inclusion-...
4,Les enjeux de propriété intellectuelle dans l'...,Les enjeux de propriété intellectuelle dans l'...,https://www.economie.gouv.fr/apie/les-enjeux-d...

In [ ]:
# Azure Text analysis API

# AI Research on France

In [5]:
import pandas as pd
research = pd.read_csv("C:/Users/Jhonnatan/Documents/GitHub/Impact-of-AI-in-organizations/Datasets/scopus.csv")
research.head()
#research.describe()

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,ISBN,CODEN,PubMed ID,Language of Original Document,Abbreviated Source Title,Document Type,Publication Stage,Open Access,Source,EID
0,Ahmad Husairi M.; Rossi P.,"Ahmad Husairi, Mariyani (57222988933); Rossi, ...",57222988933; 56289040400,Delegation of purchasing tasks to AI: The role...,2024,Decision Support Systems,179,NaN,114166,NaN,...,NaN,DSSYD,NaN,English,Decis Support Syst,Article,Final,NaN,Scopus,2-s2.0-85181774528
1,Pagallo U.; O’Sullivan S.; Nevejans N.; Holzin...,"Pagallo, Ugo (19337758400); O’Sullivan, Shane ...",19337758400; 57205361372; 57205364562; 2339628...,The underuse of AI in the health sector: Oppor...,2024,Health and Technology,14,1,NaN,1,...,NaN,NaN,NaN,English,Health Technol.,Review,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85179329265
2,Karapantelakis A.; Alizadeh P.; Alabassi A.; D...,"Karapantelakis, Athanasios (35113103400); Aliz...",35113103400; 58540431900; 58540313100; 5722251...,Generative AI in mobile networks: a survey,2024,Annales des Telecommunications/Annals of Telec...,79,1-2,NaN,15,...,NaN,ANTEA,NaN,English,Ann Telecommun,Article,Final,NaN,Scopus,2-s2.0-85168263912
3,Beljaards L.; Pezzotti N.; Rao C.; Doneva M.; ...,"Beljaards, Laurens (57219764499); Pezzotti, Ni...",57219764499; 58150639100; 57222130969; 2398862...,AI-based motion artifact severity estimation i...,2024,Medical Physics,NaN,NaN,NaN,NaN,...,NaN,MPHYA,NaN,English,Med. Phys.,Article,Article in press,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85181252141
4,Borghesani P.; Herwig N.; Antoni J.; Wang W.,"Borghesani, P. (54929106000); Herwig, N. (5721...",54929106000; 57210189917; 7003925399; 55319557300,A Fourier-based explanation of 1D-CNNs for mac...,2023,Mechanical Systems and Signal Processing,205,NaN,110865,NaN,...,NaN,MSSPE,NaN,English,Mech Syst Signal Process,Article,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85174572960

In [7]:
import pandas as pd
research_AI_BS = pd.read_csv("C:/Users/Jhonnatan/Documents/GitHub/Impact-of-AI-in-organizations/Datasets/scopus_AI_business.csv")
research_AI_BS.head()
research_AI_BS.describe()

,Year,Page start,Page end,Page count,Cited by,Molecular Sequence Numbers,Tradenames,Manufacturers,Conference code,PubMed ID
count,198.000000,136.000000,135.000000,135.000000,198.000000,0.0,0.0,0.0,58.000000,1.000000e+01
mean,2019.888889,1609.095588,1653.533333,34.451852,21.257576,NaN,NaN,NaN,197291.982759,2.704737e+07
std,5.176850,8643.930230,8672.326029,73.350998,54.921534,NaN,NaN,NaN,59949.320927,7.629980e+06
min,1991.000000,1.000000,6.000000,2.000000,0.000000,NaN,NaN,NaN,83470.000000,1.902097e+07
25%,2020.000000,67.500000,115.000000,7.000000,0.000000,NaN,NaN,NaN,164379.750000,2.065867e+07
50%,2022.000000,194.000000,260.000000,13.000000,2.500000,NaN,NaN,NaN,184649.000000,2.338612e+07
75%,2023.000000,516.750000,536.000000,22.000000,15.750000,NaN,NaN,NaN,243479.000000,3.487929e+07
max,2024.000000,95376.000000,95396.000000,489.000000,411.000000,NaN,NaN,NaN,304259.000000,3.721016e+07

# AI FR News

In [1]:
import pandas as pd
DS = pd.read_csv("C:/Users/Jhonnatan/Documents/GitHub/Impact-of-AI-in-organizations/Datasets/news_articles.csv")
DS.head()

,Title,Link,Description,Publication Date
0,"AI: Virtual reality, concrete ambitions - Busi...",https://world.businessfrance.fr/nordic/2023/04...,"In 2018, France was one of the first countries...",NaN
1,Keep an AI on France #1: Overview - Business F...,https://world.businessfrance.fr/nordic/2019/03...,NaN,NaN
2,FAQ du Volontariat International,https://mon-vie-via.businessfrance.fr/faq-vie-via,"Contrat, salaire, logement, déplacements, vaca...",NaN
3,Keep an AI on France #2: Education - Business ...,https://world.businessfrance.fr/nordic/2019/03...,NaN,NaN
4,AI France SUMMIT 2020 : l’Intelligence artific...,https://www.techtalks.fr/ai-france-summit-2020...,Près de 2500 participants sont conviés à l’AI ...,04/03/2020

# Data Scientist vs size of Datasets (France experiment 2016)

In [12]:
import pandas as pd
DS = pd.read_csv("C:/Users/Jhonnatan/Documents/GitHub/Impact-of-AI-in-organizations/Datasets/Data_Scientists_France.csv")
DS.head()

,ID,DS_1,DS_2,DS_3,DS_4,DS_5,W_1,W_2,W_3,W_4,W_5,W_6,W_7,W_8,W_9
0,1,No,No,Large,No,Yes,Intel,Yes,1400,4,32,No,Python,Python,Python
1,2,No,No,Large,No,No,AMD,No,800,2,16,No,Python,Python,Python
2,3,No,No,Medium,No,Yes,Intel,No,2400,4,24,No,R,R,R
3,4,No,No,Large,No,Yes,Intel,Yes,1000,2,4,No,R,R,R
4,5,No,Yes,Medium,Yes,Yes,Intel,No,900,2,12,No,"R, Python",R,R